### ISSUE TITLE
No single LoRA model can score on Disambiguation

### ISSUE THREAD

**Issue by sunyuhan19981208** [sail-sg/lorahub#10]
# Description
I tested almost all the lora models on the hugging face lorahub, but no single lora can score on Disambiguation subset. Is it really possible that merging weights makes the miracle happend? And without the Disambiguation subset, all the lora models are pretty similar to the flan-t5-large result on BBH.
Some lora can not be loaded as the filename is different from hugging face model id. I will fix that problem later but the current result is strange.
## Code
``` python
import threading
import os
from lorahub.constant import LORA_MODULE_NAMES
def run(device:int):
    for i, lora in enumerate(LORA_MODULE_NAMES):
        if i%8!=device:
            continue
        loraname = lora.split('/')[-1]
        print(f'thread:{device} is testing {loraname}')
        os.system(f'CUDA_VISIBLE_DEVICES={device} python reproduce_bbh.py >log/{loraname}.log 2>log/{loraname}.err '+
                  f'--lora_model /data/sdb/sunyuhan/exp/lorahub_models/{loraname}')
    print(device)
threads = [threading.Thread(target=run, args=[i])for i in range(8)]
for t in threads:
    t.start()
for t in threads:
    t.join()
print("Thread has finished.")
```
## TOP5 LoRA vs flan-T5-large
Look at the radar chart, all the models are similar and none can score on Disambiguation subset:
![Figure_1](https://github.com/sail-sg/lorahub/assets/50269851/6a43973e-f54e-4afc-b576-b8f315510035)

**Comment by sunyuhan19981208** [comment]
I am trying to figure out where the real contribution of improvement come from. I have ever thought that the improvement came from the bias of every single lora, but I found that may be not true..

**Comment by sunyuhan19981208** [comment]
here is the outputs of `disambiguation_qa`:
``` python
(Pdb) outputs
['The analyst', 'The director', 'The scientist shares a story', 'The assistant asked the physician if she could borrow some money.', 'The cook']
(Pdb) ground_truths
['(B)', '(C)', '(C)', '(A)', '(B)']
```

**Comment by SivilTaram** [comment]
@sunyuhan19981208 Why not trying to reproduce the results of lorahub on these datasets before posting the question?

**Comment by sunyuhan19981208** [comment]
@SivilTaram https://github.com/sunyuhan19981208/single_lora_results here are every single lora results on BBH, I am too busy these days... I haven't reproduce the main result of lorahub, but I believe what you show in paper is true.

**Comment by SivilTaram** [comment]
@sunyuhan19981208 Thanks for sharing! I will investigate it for a while and get back if I get something interesting.
