### ISSUE TITLE
can lorahub be used in non llm tasks

### ISSUE THREAD

**Issue by francqz31** [sail-sg/lorahub#16]
Hello Author,
I just wanted to ask if lorahub can be used on non llm tasks, for example in things like text to speech in vits for example https://github.com/jaywalnut310/vits . 

Thanks in advance.

**Comment by SivilTaram** [comment]
@francqz31 Thanks for your awesome idea, and I think yes, it could be applied to non llm tasks! Since we are not experts on text-to-speech, we do not explore more on this kind of possibilities.

**Comment by Chengsong-Huang** [comment]
@francqz31 And there is some work that have proved that lorahub can be used in other domain like computer vision
 https://www.semanticscholar.org/reader/a09cbe54f842b9b243de4307349cb2800f3044d3
