### ISSUE TITLE
Release of Code for Finetuning Lora modules of FLAN and evaluating the Finetuned Models.

### ISSUE THREAD

**Issue by prateeky2806** [sail-sg/lorahub#17]
Hi, thank you for your good work!

I was wondering if you could provide the code used to Finetune these Lora modules on the flan datasets, along with the flan data loading scripts, the validation data used to tune hyperparameters, and perform the model selection. It would be very useful to everyone in general. 

Thanks,
Prateek

**Comment by SivilTaram** [comment]
@prateeky2806 Hi Prateek, thanks for your interest on our work!

I have uploaded the script to run the lora training at [https://github.com/sail-sg/lorahub/blob/main/run.sh], and you can follow the script to train the model. It requires you to download the flan task dataset, and you can follow the python file `download_flan.py` to achieve it. Thanks!

**Comment by prateeky2806** [comment]
Hi, I was trying to download the FLAN datasets using the script. Seems like the datasets tag "conceptofmind/FLAN_2022" is not available on hugging face anymore. Would it be possible for you to upload the data you have to huggingface or share a copy privately with me? 

Thanks,
Prateek
