### ISSUE TITLE
FLAN datasets not available on Huggingface.

### ISSUE THREAD

**Issue by prateeky2806** [sail-sg/lorahub#18]
Hi @SivilTaram, thank you for sharing the training scripts!

I was trying to download the FLAN datasets using the script. Seems like the datasets tag "conceptofmind/FLAN_2022" is not available on hugging face anymore. Would it be possible for you to upload the data you have to huggingface or share a copy privately with me? This is critical for reproducing some of the experiments on my end. 

Thanks,
Prateek

**Comment by JornyWan** [comment]
I met same problem, which is showed as follows:
"
FileNotFoundError: Couldn't find a dataset script at /data/wanc/lorahub/conceptofmind/FLAN_2022/FLAN_2022.py or any data file in the same directory. Couldn't find 'conceptofmind/FLAN_2022' on the Hugging Face Hub either: FileNotFoundError: Dataset 'conceptofmind/FLAN_2022' doesn't exist on the Hub
"

**Comment by SivilTaram** [comment]
Hi @prateeky2806 @JornyWan, I'm not sure why the author removed the datasets, but I have tried my best to upload the processed dataset (i.e., the files under the `flan_task` folder in the script) at https://huggingface.co/datasets/lorahub/flanv2.

You may use the following script to download the dataset:
```
git clone https://huggingface.co/datasets/lorahub/flanv2
```

Please let me know if you have further questions. Thanks!

**Comment by prateeky2806** [comment]
Thanks for providing the dataset. This works for me.

**Comment by JornyWan** [comment]
Thanks for providing it! One more question about this is i see that it only got about several thousands rows and only got one task? is that all the task you used in your lora training, because i see you got 196 tasks but here is only one task dataset.

**Comment by prateeky2806** [comment]
Hi @JornyWan, the preview in Huggingface is messed up but if you look at the files there are files corresponding to all the datasets.

**Comment by SivilTaram** [comment]
@JornyWan Just as suggested by Prateek :)

**Comment by JornyWan** [comment]
@prateeky2806 @SivilTaram  thanks, and i use lfs to download it successfully.
BTW, do you have the code to compose the lora trained by your code- train_model.py to compose them and evaluate it, then i can try to reproduce the results which is trained by myself. ( using the same training dataset, model and codes)

**Comment by SivilTaram** [comment]
Feel free to try it here: https://github.com/sail-sg/lorahub/blob/main/reproduce_bbh.py

@JornyWan

**Comment by taehyunzzz** [comment]
Hi, I did not get how exactly to download the flan v2 files.
My understanding is to git clone the repo above, and do some other scripting for downloading each dataset using git lfs ...?

**Comment by SivilTaram** [comment]
@taehyunzzz Hi, your understanding is correct. You can use `git lfs pull` to download all datasets
