### ISSUE TITLE
repaired an error in reproduce_bbh.py (shuffle seed)

### ISSUE THREAD

**Issue by JornyWan** [sail-sg/lorahub#19]
Hi there, i found i could not use shuffle with seed, if anyone meets this problem, you can use the following codes to replace the original one, which is around line62:
        random.seed(42)
        shuffled_set = list(zip(example_inputs, examples_outputs))
        random.shuffle(shuffled_set)
        example_inputs, examples_outputs = zip(*shuffled_set)

**reproduce_bbh.py**

**Comment by SivilTaram** [comment]
@JornyWan thanks for the feedback! Would you mind creating a pull request for the bug (not sure why I can run it, maybe because of python version)?

**Comment by JornyWan** [comment]
@SivilTaram  ok, i will do it
