### ISSUE TITLE
Using with CausalLM models

### ISSUE THREAD

**Issue by aksh555** [sail-sg/lorahub#25]
Hi, thanks for the great library! Can the LoRA composition and weight learning approach be used with LoRA modules trained from AutoModelForCausalLM? If so, do you have any supporting scripts etc.

Thanks!

**Comment by SivilTaram** [comment]
@aksh555 Hi, thanks for your interest on our work! Yes definitely it should work well. First, you should train LoRA module based on your base model (e.g., Llama), then you can use https://github.com/sail-sg/lorahub/blob/main/example.py to do lorahub learning.

**Comment by aksh555** [comment]
Thanks @SivilTaram but the current [algorithm.py](https://github.com/sail-sg/lorahub/blob/df73afe5f38d9ff0fd1cd43774be51c79c581cc3/lorahub/algorithm.py#L33) supports only `AutoModelForSeq2SeqLM`, so for using with Llama like model, the loading and dataset preparation needs to be changed?

**Comment by SivilTaram** [comment]
@aksh555 Thanks for reporting! Yes this should be fixed easily and I will try to fix it in 1 week. You can also try to directly modify it into `AutoModel` and then see if that works for your case! Thanks!

**Comment by yaolu-zjut** [comment]
> @aksh555 Thanks for reporting! Yes this should be fixed easily and I will try to fix it in 1 week. You can also try to directly modify it into `AutoModel` and then see if that works for your case! Thanks!

Hi, @aksh555 and @SivilTaram , do you achieve this and can you share this code with me? Thanks very much

**Comment by Msirisme** [comment]
> > [@aksh555](https://github.com/aksh555) Thanks for reporting! Yes this should be fixed easily and I will try to fix it in 1 week. You can also try to directly modify it into `AutoModel` and then see if that works for your case! Thanks!
> 
> Hi, [@aksh555](https://github.com/aksh555) and [@SivilTaram](https://github.com/SivilTaram) , do you achieve this and can you share this code with me? Thanks very much

I also want to know if you have accomplished this task.
