### ISSUE TITLE
How to use local LoRA trained with train_model.py

### ISSUE THREAD

**Issue by Weifan1226** [sail-sg/lorahub#27]
Hi team!

I trained my own LoRA with train_model.py. Then I have a folder called 'demo' which contains my LoRA model (located in /lorahub/demo) . If I would like to use it in the process of lorahub_learning, should I add 'lorahub/demo' to LORA_MODULE_NAMES?  I have tried but failed somehow.

Hope to get your guidance.

Thanks!
Fanjunduo Wei

**Comment by SivilTaram** [comment]
@Weifan1226 Thanks for your interest on our work! You can upload the lora module to HuggingFace, and then write the repo name into LORA_MODULE_NAMES.

For example, if I upload the lora module to hf.co/SivilTaram/demo, then I should add SivilTaram/demo to the names.

**Comment by yaolu-zjut** [comment]
Hi, may I ask how do you standardize the training of so many datasets?

**Comment by SivilTaram** [comment]
@yaolu-zjut Hello, thanks for your question! We standardize the training format of these different datasets, truncate the number of training examples to the maximum of 10k, and train LoRA modules using the same hyper-parameter.

**Comment by yaolu-zjut** [comment]
> @yaolu-zjut Hello, thanks for your question! We standardize the training format of these different datasets, truncate the number of training examples to the maximum of 10k, and train LoRA modules using the same hyper-parameter.

Hi [SivilTaram](https://github.com/SivilTaram), thanks for your reply. Would you please share the training format of these different datasets, since there are many tasks belonging to various tasks, like QA, multiple choice, text generation, etc.

**Comment by SivilTaram** [comment]
@yaolu-zjut Sure you can find the training dataset at https://huggingface.co/datasets/lorahub/flanv2

**Comment by yaolu-zjut** [comment]
> @yaolu-zjut Sure you can find the training dataset at https://huggingface.co/datasets/lorahub/flanv2

Thanks!
