### ISSUE TITLE
About training examples

### ISSUE THREAD

**Issue by lucasjinreal** [sail-sg/lorahub#5]
Hi, if using Chinese, how many examples does it need to train this lora?

Also ,will the lora effect original model ablility heavily?

**Comment by SivilTaram** [comment]
@lucasjinreal Hi, if you have a Chinese base model, it should not require too many examples to train a lora module to fit you downstream task. I'm not sure if I get it correctly, but based on my experience, the lora module does not affect a lot on the parameters, and so does not "effect original model ability heavily". But it depends on your training method
