### ISSUE TITLE
About LoraHub adapters

### ISSUE THREAD

**Issue by soroush-tabesh** [sail-sg/lorahub#7]
Nice work!

I needed clarification about the adapters you released on HF; the base model is flan-t5, and the adapters are trained on some Flan tasks! Am I mistaking something, or they're taught on the seen data? e.g., the ANLI task is a Flan2021 task(which probably flan-t5 has seen) and is included in your hub.

Also, are you planning to release the code to reproduce the numbers in your paper in the near future?

Thanks.

**Comment by SivilTaram** [comment]
@soroush-tabesh Hello, thanks for your interest on our work!

Yes, in all of our experiments, we use the **tasks already seen by FLAN-T5** to compare, since it does not introduce unfair advantage of our method (no more new tasks or new datasets).

Sure, we're still cleaning the code and will release the full script to reproduce our results on BBH, thanks!

Best,
Qian

**Comment by SivilTaram** [comment]
@soroush-tabesh Hello! We have released the reproduce script in `reproduce_bbh.py`. Please checkout the script! Please let me know if you have any follow-up problems!

**Comment by soroush-tabesh** [comment]
@SivilTaram Great. thanks!

**Comment by StarLooo** [comment]
Hello, LoRAHub is a very interesting work! 
I have the following two questions about the LoRA modules mentioned in the paper:
(1) According to the original paper, the FLAN-2022 Collection used for Flan-T5 instruction tuning consists of as many as 1836 tasks. However, in LoRAHub, it seems that only 196 tasks were used to train the LoRA modules. Can you please clarify if there is any misunderstanding here or if you selected these 196 tasks from the pool of 1836 tasks?
(2) LoRAHub trained each LoRA module using the same tasks as Flan-T5 for fairness. However, it seems that Flan-T5 sampled train examples from different tasks during training and did not use all the samples. Does this mean that even though LoRAHub's LoRA modules use the same tasks as Flan-T5, they may still use samples that Flan-T5 has not seen?
